Merged PR 2349: Fix warnings on Linux
Fix warnings on Linux

1. lotus/core/graph/model.cc:51:32: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
2. Remove unused member variable: graph_transformer_

clang treats these two warnings as error.